# Generated by Django 5.2.10 on 2026-02-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('likes', models.ManyToManyField(related_name='liked_posts', to='employee.employee')),
            ],
            options={
                'db_table': 'residentpost',
            },
        ),
    ]
